### ISSUE TITLE
[Feature Request] 能否发布FreeBSD amd64的二进制运行包？

### ISSUE THREAD

**Issue by egg1234** [deatil/doak-cron#2]
能否发布FreeBSD amd64的二进制运行包？

谢谢

**Comment by deatil** [comment]
加了。可以试下

**Comment by egg1234** [comment]
已经完美运行，不过好像版本号没有改过来

./doak-cron cron version
计划任务当前版本号为:  1.0.8

谢谢

**Comment by deatil** [comment]
@egg1234 好像是忘记了😂
后面有更新在一起改了
